# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindThingPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upfile')),
                ('thingName', models.CharField(default='NULL', max_length=30)),
                ('findPosition', models.CharField(default='NULL', max_length=50)),
                ('description', models.CharField(default='NULL', max_length=200)),
                ('findTime', models.CharField(default='NULL', max_length=40)),
                ('contactByQQ', models.CharField(default='NULL', max_length=20)),
                ('contactByAddress', models.CharField(default='NULL', max_length=40)),
                ('contactByWeChat', models.CharField(default='NULL', max_length=50)),
                ('contactByEmail', models.CharField(default='NULL', max_length=50)),
                ('contactByPhone', models.CharField(default='NULL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LostThingPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upfile')),
                ('thingName', models.CharField(default='NULL', max_length=30)),
                ('lostPosition', models.CharField(default='NULL', max_length=50)),
                ('description', models.CharField(default='NULL', max_length=200)),
                ('lostTime', models.CharField(default='NULL', max_length=40)),
                ('contactByQQ', models.CharField(default='NULL', max_length=20)),
                ('contactByAddress', models.CharField(default='NULL', max_length=40)),
                ('contactByWeChat', models.CharField(default='NULL', max_length=50)),
                ('contactByEmail', models.CharField(default='NULL', max_length=50)),
                ('contactByPhone', models.CharField(default='NULL', max_length=20)),
            ],
        ),
    ]
