# Generated by Django 2.1.3 on 2019-05-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFindApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostthingpeople',
            name='contactByAddress',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lostthingpeople',
            name='contactByEmail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lostthingpeople',
            name='contactByPhone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostthingpeople',
            name='contactByQQ',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostthingpeople',
            name='contactByWeChat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lostthingpeople',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lostthingpeople',
            name='lostPosition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lostthingpeople',
            name='lostTime',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lostthingpeople',
            name='thingName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
