# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFindApp', '0002_auto_20190502_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findthingpeople',
            name='contactByAddress',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='findthingpeople',
            name='contactByEmail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='findthingpeople',
            name='contactByPhone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='findthingpeople',
            name='contactByQQ',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='findthingpeople',
            name='contactByWeChat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='findthingpeople',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='findthingpeople',
            name='findPosition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='findthingpeople',
            name='findTime',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='findthingpeople',
            name='thingName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
